[project]
name = "device-systems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dj107-il", email = "diegoballes4@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic[email]>=2.13.5",
    "sqlalchemy>=2.0.54",
    "uvicorn[standard]>=0.52.4",
]

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
